spring:
  application:
    name: spring-boot-today

springfox:
  documentation:
    auto-startup: false

server:
  port: 8764

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.training.springbootinitial]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
